import fs from 'fs';
const I='material-cliente/ig/';
const img={ 'lisas-permanente':'Db6O5boT0g7','permanente-1-4-disenos':'Dd8_TrfzXLB','permanente-full-diseno':'DdgzKpIzlDc','permanente-francesa':'DcjC0Pele1R','efectos':'DccISjLT4fp','polygel-lisas':'Dcv8o6OzJFf','polygel-francesa':'DcWdiKDlfeU','polygel-full-diseno':'DcHeg7oTP9J','kapping':'DcWa0FSzm0X','hero':'DcWb1LeTRsw','x-animal':'Dc37roMTtU5','x-carey':'DdhrhQqz2iv','x-francesas':'Dd2YHaVlb6o','x-lunares':'DcRpeQ3z90d'};
for(const [k,v] of Object.entries(img)) fs.copyFileSync(I+v+'.jpg','img/servicios/'+k+'.jpg');
const S=[
 {id:'lisas-permanente',nombre:'Esmaltado permanente · Lisas',categoria:'Esmaltado permanente',precio:18500,descripcion:'Esmaltado permanente en un solo color, con preparación y acabado prolijo. Dura semanas con brillo de espejo.',portada:'servicios/lisas-permanente.jpg',fotos:['servicios/x-lunares.jpg'],etiqueta:'',origen:'Lista de precios (historia destacada "Precios"); foto: post Db6O5boT0g7'},
 {id:'permanente-1-4-disenos',nombre:'Esmaltado permanente + diseños',categoria:'Esmaltado permanente',precio:20990,precio_prefijo:'desde',descripcion:'Tu esmaltado con 1 a 4 uñas diseñadas: puntitos, líneas, animal print, lo que quieras. Desde $20.990 con 1 diseño hasta $23.990 con 4.',portada:'servicios/permanente-1-4-disenos.jpg',fotos:['servicios/x-animal.jpg'],etiqueta:'',origen:'Lista de precios; foto: post Dd8_TrfzXLB'},
 {id:'permanente-full-diseno',nombre:'Esmaltado permanente · Full diseño',categoria:'Esmaltado permanente',precio:24990,descripcion:'Las diez uñas con diseño, un set completo hecho a mano. Diseños complejos o mano alzada pueden tener un valor adicional.',portada:'servicios/permanente-full-diseno.jpg',fotos:[],etiqueta:'Más pedido',destacado:true,origen:'Lista de precios; foto: post DdgzKpIzlDc'},
 {id:'permanente-francesa',nombre:'Francesa o Degradé',categoria:'Esmaltado permanente',precio:21990,descripcion:'Francesas clásicas, de colores o con carey; también degradé. Un infaltable que siempre se ve elegante.',portada:'servicios/permanente-francesa.jpg',fotos:['servicios/x-carey.jpg','servicios/x-francesas.jpg'],etiqueta:'',origen:'Lista de precios; foto: post DcjC0Pele1R'},
 {id:'efectos',nombre:'Efectos: Perlado, Aurora u Ojo de gato',categoria:'Extras',precio:2000,precio_prefijo:'+',descripcion:'Suma un efecto especial a cualquier servicio: perlado, aurora u ojo de gato. Se agrega al valor del servicio elegido.',portada:'servicios/efectos.jpg',fotos:[],etiqueta:'',origen:'Lista de precios; foto: post DccISjLT4fp'},
 {id:'polygel-lisas',nombre:'Extensión de uñas Polygel · Lisas',categoria:'Extensión polygel',precio:26990,descripcion:'Largo y forma a tu gusto con polygel, liviano y resistente, en un solo color.',portada:'servicios/polygel-lisas.jpg',fotos:[],etiqueta:'',origen:'Lista de precios; foto: post Dcv8o6OzJFf'},
 {id:'polygel-francesa',nombre:'Polygel · Francesa o Degradé',categoria:'Extensión polygel',precio:28990,descripcion:'Extensión en polygel con francesa o degradé. Como la francesa burdeo que ves aquí.',portada:'servicios/polygel-francesa.jpg',fotos:[],etiqueta:'',origen:'Lista de precios; foto: post DcWdiKDlfeU'},
 {id:'polygel-full-diseno',nombre:'Polygel · Full diseño',categoria:'Extensión polygel',precio:31990,descripcion:'Extensión en polygel con diseño en todas las uñas. Desde $27.990 con 1 diseño; el full diseño es el set completo.',portada:'servicios/polygel-full-diseno.jpg',fotos:[],etiqueta:'',origen:'Lista de precios; foto: post DcHeg7oTP9J'},
 {id:'kapping',nombre:'Kapping / nivelación',categoria:'Extras',precio:4000,precio_prefijo:'+',descripcion:'Refuerzo y nivelación de la uña natural: +$4.000 en hard gel y +$7.000 en polygel.',portada:'servicios/kapping.jpg',fotos:[],etiqueta:'',origen:'Lista de precios; foto: post DcWa0FSzm0X'},
 {id:'limpieza-facial',nombre:'Limpieza facial',categoria:'Cosmetología',precio:null,descripcion:'Limpieza facial profunda con cosmetología. Valor a consultar según tu tipo de piel.',portada:'',fotos:[],etiqueta:'Cosmetología',origen:'Bio y post DZqo43YTv73 (sin precio publicado)'}
];
S.forEach((s,i)=>{s.duracion_min=60;s.orden=i+1;s.visible=true;s.destacado=!!s.destacado;if(!s.precio_prefijo)s.precio_prefijo='';fs.writeFileSync('data/servicios/'+s.id+'.json',JSON.stringify(s,null,2))});
const dias=['lunes','martes','miércoles','jueves','viernes','sábado','domingo'];
fs.writeFileSync('data/ajustes.json',JSON.stringify({
 contacto:{whatsapp:'56911112222',mensaje_defecto:'Hola Naayú! Quiero agendar una hora en Lunaria 🌙',instagram:'lunariaestudio.cl',correo:''},
 ubicacion:{direccion:'Metro Villa Frei, Ñuñoa, Santiago',comuna:'Ñuñoa',ciudad:'Santiago',region:'Región Metropolitana',referencia:'A 8 minutos caminando del Metro Villa Frei (Línea 3)'},
 portada:{titulo:'Tu momento de regaloneo',bajada:'Uñas y cuidado personal con atención 100% personalizada, una a una. Estudio en Ñuñoa, a pasos del Metro Villa Frei.',lema:'Uñas · Cosmetología'},
 reservas:{activas:true,duracion_bloque_min:60,anticipacion_horas:2,dias_adelante:30},
 horario:dias.map(d=>({dia:d,cerrado:d==='domingo',abre:'10:00',cierra:'19:00',pausa_desde:'',pausa_hasta:''})),
 pagos:['Transferencia','Débito','Crédito','Efectivo']
},null,2));
fs.writeFileSync('data/flyer.json',JSON.stringify({mostrar:false,popup:false,imagen:'',titulo:'',texto:'',mensaje_whatsapp:''},null,2));
fs.writeFileSync('data/testimonios.json',JSON.stringify({items:[]},null,2));
fs.writeFileSync('sitio.config.json',JSON.stringify({nombre:'Lunaria Estudio',nombre_corto:'Lunaria',rubro:'Manicure, uñas polygel y cosmetología',schema_tipo:'BeautySalon',dominio:'https://lunariaestudio.vercel.app',repo:'Bemol69/lunariaestudio.cl',seo:{titulo:'Lunaria Estudio · Uñas y cosmetología en Ñuñoa, Metro Villa Frei',descripcion:'Esmaltado permanente, extensión polygel y limpiezas faciales en Ñuñoa. Atención personalizada a pasos del Metro Villa Frei. Reserva tu hora online.',imagen:'servicios/hero.jpg'},colores:{tema:'#2B1F2E'}},null,2));
